export const DEFAULT_PRIMARY_UPI =
  process.env.NEXT_PUBLIC_DEFAULT_UPI || "7489988065@ibl";

export const DEFAULT_SECONDARY_UPI =
  process.env.NEXT_PUBLIC_SECONDARY_UPI || DEFAULT_PRIMARY_UPI;

export const PAYMENT_UPI_IDS = [DEFAULT_PRIMARY_UPI, DEFAULT_SECONDARY_UPI];

export const PAYMENT_ACCOUNT_NUMBER = "378705500156";
export const PAYMENT_IFSC_CODE = "ICIC003787";
